### ISSUE TITLE
Cgroup problems

### ISSUE THREAD

**Issue by Jason-ZW** [kata-containers/documentation#684]
# Description of problem

Using osbuilder build the image. When running pod there some cgroups error. Using the official `kata-containers.img` no error.
```
failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused \"process_linux.go:449: container init caused \\\"process_linux.go:415: setting cgroup config for procHooks process caused \\\\\\\"failed to write \\\\\\\\\\\\\\\"b *:* m\\\\\\\\\\\\\\\" to \\\\\\\\\\\\\\\"/sys/fs/cgroup/devices/kubepods/besteffort/poda64e679d-6c77-4e6c-b3c8-1415676735ad/9759c0db984a474cc5977c385272ee5d65fc857a0fd3469d68bbcda1508e338c/devices.allow\\\\\\\\\\\\\\\": write /sys/fs/cgroup/devices/kubepods/besteffort/poda64e679d-6c77-4e6c-b3c8-1415676735ad/9759c0db984a474cc5977c385272ee5d65fc857a0fd3469d68bbcda1508e338c/devices.allow: operation not permitted\\\\\\\"\\\"\": unknown
```

**Comment by lifupan** [comment]
@Jason-ZW  what's the distro you used for building your image?

**Comment by Jason-ZW** [comment]
@lifupan both I try `ubuntu` & `centos`

**Comment by lifupan** [comment]
@Jason-ZW 
Can you give much more steps on how to reproduce this issue?

**Comment by Jason-ZW** [comment]
@lifupan 
Using Kubernetes kata-runtime with QEMU running k3s Pod. Kata using custom `.img` which built follow the https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#create-a-rootfs-image
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-server-1
  namespace: default
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: k3s-server-1
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: k3s-server-1
      annotations:
        io.katacontainers.config.agent.kernel_modules: "br_netfilter"
    spec:
      runtimeClassName: kata
      containers:
              # - image: rancher/k3s:v1.18.3-k3s1
      - image: zhenyangzhao/k3s:demo
        imagePullPolicy: Always
        name: k3s-server-1
        command: ["k3s", "server", "--snapshotter=native"]
        ports:
        - containerPort: 6443
          name: 6443tcp01
          protocol: TCP
        - containerPort: 8472
          name: 8472tcp01
          protocol: TCP
        - containerPort: 10250
          name: 10250tcp01
          protocol: TCP
        resources:
          limits:
            memory: "2048Mi"
            cpu: "1"
          requests:
            memory: "1024Mi"
            cpu: "1"
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        volumeMounts:
        - mountPath: /etc/machine-id
          name: machineid
        - mountPath: /run
          name: tmpfsrun
        - mountPath: /var/run
          name: tmpfsvar
        - mountPath: /var/lib/rancher/k3s
          name: k3slib
      volumes:
      - name: machineid
        hostPath:
          path: /etc/machine-id
          type: FileOrCreate
      - name: tmpfsrun
        emptyDir:
          medium: "Memory"
      - name: tmpfsvar
        emptyDir:
          medium: "Memory"
      - name: k3slib
        emptyDir: {}
      restartPolicy: Always
```
